name: innovaccer_design_system
description: A package that contains the core UI components as per the Innovaccer design system.
version: 0.1.1
repository: https://github.com/innovaccer/mobile-design-system
homepage: https://design.innovaccer.com/0ee0e5c39/v/0/p/99faa4-masala-design-system

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 2.3.3
  url_launcher: 6.3.1
  pinput: 5.0.0
  flutter_styled_toast: 2.2.1
  flutter_linkify: 6.0.0
  sms_autofill: 2.4.1
  decimal: 2.3.3
  provider: 6.1.2
  smart_auth: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
