name: innovaccer_design_system
description: A package that contains the core UI components as per the Innovaccer design system.
version: 0.1.2
repository: https://github.com/innovaccer/mobile-design-system
homepage: https://design.innovaccer.com/0ee0e5c39/v/0/p/99faa4-masala-design-system

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.11
  url_launcher: ^6.1.7
  flutter_styled_toast: ^2.1.3
  flutter_linkify: ^5.0.2
  sms_autofill: ^2.2.0
  decimal: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1